# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

#source .path, .export and .aliases files
for file in ~/.{path,exports,aliases}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="nanotech"

# Set to this to use case-sensitive completion
export CASE_SENSITIVE="true"

# Vagrant
export VAGRANT_HOME=~/.vagrant.d

# Editor
export EDITOR="vim"

export LC_ALL=en_US.UFT-8
export LANG=en_US.UTF-8


# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)

plugins=(git vagrant django tmux tmuxinator)
if [ `uname` = "Darwin" ]; then
   plugins+=(brew osx)
fi

if [ `uname` = "Linux" ]; then
   plugins+=(archlinux)
fi

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
source ~/.zshalias
source ~/.zshenv

# Check for a .venv file. If it's there, activate it.
# has_virtualenv() {
#   if [ -e .venv ] && [ -z "$VIRTUAL_ENV" ]; then
#     workon "$@" `cat .venv`
#   fi
# }
# venv_cd () {
#   cd "$@" && has_virtualenv
# }
# alias cd="venv_cd"

# Bindings
bindkey -e


# If vim mode, than bind this key, can't live without
# CTRL-R
# bindkey "^r" history-incremental-search-backward

export PATH=/usr/local/bin:$PATH
export PATH=/opt/subversion/bin:$PATH


#Docker
eval $(docker-machine env)
#export DOCKER_HOST=tcp://192.168.10.10:2375
#export DOCKER_CERT_PATH=/Users/wijnand/.boot2docker/certs/boot2docker-vm
#export DOCKER_TLS_VERIFY=1

#Yeoman / NPM
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

# Docker (default for Vagrant based boxes)
#export DOCKER_HOST=tcp://localhost:2375

# Autojump
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew  --prefix)/etc/profile.d/autojump.sh

# for golang
# # mkdir $HOME/go
# # mkdir -p $GOPATH/src/github.com/user
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# export PATH=/Users/wijnand/kubernetes/platforms/darwin/amd64:$PATH

# The next line enables shell command completion for gcloud.
source '/Users/wijnand/google-cloud-sdk/completion.zsh.inc'


# The next line updates PATH for the Google Cloud SDK.
source '/Users/wijnand/google-cloud-sdk/path.zsh.inc'

# The next line enables shell command completion for gcloud.
source '/Users/wijnand/google-cloud-sdk/completion.zsh.inc'



# added by travis gem
[ -f /Users/wijnand/.travis/travis.sh ] && source /Users/wijnand/.travis/travis.sh

# Terraform
export TF_LOG=1

# Atlas api token
export ATLAS_TOKEN="SUyZNVXQ3JfM1A.atlasv1.V3ygEucwmjTlTTv64wbxmu3ddjI4BH3TvUsy80sqm3JYzatZ5zLr6T40w8tZKdgS2n8"

# ssh config autocomplete
_complete_ssh_hosts ()
{
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    comp_ssh_hosts=`cat ~/.ssh/known_hosts | \
        cut -f 1 -d ' ' | \
        sed -e s/,.*//g | \
        grep -v ^# | \
        uniq | \
        grep -v "\[" ;
    cat ~/.ssh/config | \
        grep "^Host " | \
        awk '{print $2}'
    `
    COMPREPLY=( $(compgen -W "${comp_ssh_hosts}" -- $cur))
    return 0
}
complete -F _complete_ssh_hosts ssh

# Openconnect (blendle)
 alias baremetal="sudo openconnect --no-xmlpost -u rqcxadmin https://95.211.182.91:443"

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#DCOS
alias dma="dcos marathon app"
alias dm="dcos marathon"

#path to the DCOS CLI binary
if [[ "$PATH" != *"/Users/wijnand/dcos/bin"* ]];
  then export PATH=$PATH:/Users/wijnand/dcos/bin;
  fi
